"use client";

import { BookOpen, Compass, Leaf, Map, Medal, Sparkles } from "lucide-react";
import { ProgressBar } from "./ProgressBar";
import { REGION_META } from "@/lib/world";
import { getProgressPercent } from "@/lib/game";
import type { GameState } from "@/lib/types";

export function JournalPanel({ state }: { state: GameState }) {
  const species = state.discoveries.filter((item) => item.isSpecies);
  return <div className="thin-scrollbar h-full overflow-y-auto pr-1"><div className="mb-5 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl border border-[#e8c77b]/20 bg-[#e8c77b]/10 text-[#f4dca3]"><BookOpen size={18} /></div><div><div className="text-sm font-semibold text-[#eaffef]">Diário de campo</div><div className="text-[9px] uppercase tracking-[0.16em] text-[#78958a]">caderno do explorador</div></div></div><div className="mb-4 rounded-2xl border border-white/8 bg-[#071614]/45 p-4"><div className="flex items-end justify-between"><div><div className="text-[10px] uppercase tracking-[0.18em] text-[#78958a]">patente atual</div><div className="mt-1 text-2xl font-semibold tracking-[-0.05em] text-[#f2ffe9]">{state.profile.levelName}</div></div><div className="text-right"><div className="font-mono text-xl text-[#b9ff76]">{state.profile.xp}</div><div className="text-[9px] uppercase tracking-[0.15em] text-[#78958a]">XP total</div></div></div><ProgressBar value={getProgressPercent(state.profile)} className="mt-4" /><div className="mt-2 flex justify-between text-[9px] text-[#719187]"><span>nível {state.profile.level}</span><span>{state.profile.nextLevelXp > state.profile.xp ? `${state.profile.nextLevelXp - state.profile.xp} XP para o próximo` : "nível máximo"}</span></div></div>
    <div className="grid grid-cols-3 gap-2"><Stat icon={<Map size={14} />} value={state.visitedRegions.length} label="regiões" /><Stat icon={<Sparkles size={14} />} value={state.discoveries.length} label="descobertas" /><Stat icon={<Leaf size={14} />} value={species.length} label="espécies" /></div>
    <div className="mt-5"><div className="mb-3 flex items-center gap-2 text-[10px] font-medium uppercase tracking-[0.18em] text-[#7f9c91]"><Compass size={13} className="text-[#b9ff76]" /> mapa de cobertura</div><div className="space-y-2.5">{(Object.keys(REGION_META) as Array<keyof typeof REGION_META>).map((region) => { const count = state.discoveries.filter((item) => item.region === region).length; const total = region === "center" || region === "park" || region === "river" || region === "forest" || region === "industrial" || region === "residential" ? 2 : 1; return <div key={region}><div className="mb-1 flex items-center justify-between text-[10px]"><span className="text-[#b5c9bf]">{REGION_META[region].label}</span><span className="font-mono text-[#718f83]">{count}/{total}</span></div><ProgressBar value={(count / total) * 100} color={count ? "bg-[#7de7d4]" : "bg-white/15"} /></div>; })}</div></div>
    <div className="mt-5 border-t border-white/8 pt-5"><div className="mb-3 flex items-center gap-2 text-[10px] font-medium uppercase tracking-[0.18em] text-[#7f9c91]"><Medal size={13} className="text-[#e8c77b]" /> últimos registros</div>{state.discoveries.length ? <div className="space-y-2">{state.discoveries.slice(-4).reverse().map((discovery) => <div key={discovery.id} className="flex items-center gap-3 rounded-xl bg-white/[.035] p-2.5"><div className="grid h-7 w-7 place-items-center rounded-lg bg-[#b9ff76]/10 text-sm text-[#b9ff76]">{discovery.icon}</div><div className="min-w-0"><div className="truncate text-[10px] text-[#cce0d4]">{discovery.title}</div><div className="text-[9px] text-[#718f83]">+{discovery.xp} XP · {REGION_META[discovery.region].label}</div></div></div>)}</div> : <div className="rounded-xl border border-dashed border-white/10 p-4 text-center text-[10px] leading-5 text-[#6f8e83]">Seu diário está em branco.<br />Os primeiros sinais estão esperando por você.</div>}</div>
  </div>;
}

function Stat({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { return <div className="rounded-xl border border-white/8 bg-[#071614]/45 p-3"><div className="text-[#7de7d4]">{icon}</div><div className="mt-2 text-lg font-semibold text-[#eaffef]">{value}</div><div className="text-[9px] uppercase tracking-[0.13em] text-[#718f83]">{label}</div></div>; }
